# Numpy: The Basics
Created by: Kimberly Negrette B. June 2023 <br>
https://www.linkedin.com/in/kimberly-negrette/

In [32]:
# !pip install numpy <- If installation needed
import numpy as np

## Creating arrays

Arrays can be created in NumPy in several ways, such as from Python lists, using built-in functions like `zeros` and `ones`, using functions that generate random data, like `rand`, `uniform`, and `randn`, using `full` or `full_like` to create arrays of a specific size, and using `linspace` to create equally-spaced arrays.

In [8]:
# Create a 1D array with 5 elements
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [9]:
# Create a 2D array with 2 rows and 3 columns
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
# Create a 3D array with 2 matrices, each with 3 rows and 4 columns
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
              [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
# Create a 1D array of zeros with 5 elements
d = np.zeros(5)
print(d)

[0. 0. 0. 0. 0.]


In [12]:
# Create a 2D array of ones with 2 rows and 3 columns
e = np.ones((2, 3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Create a 1D array of values from 0 to 9
f = np.arange(start=0, stop=10, step=1)
print(f)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Create a 1D array of random values between 0 and 1
g = np.random.rand(5)
print(g)

[0.7222401  0.76257573 0.98019551 0.555172   0.88130083]


In [15]:
# Create a 2D array of random values between -1 and 1 with 2 rows and 3 columns
h = np.random.uniform(low=-1, high=1, size=(2, 3))
print(h)

[[ 0.3499092   0.11899448  0.2424713 ]
 [ 0.73243729  0.42878206 -0.57272142]]


In [16]:
# Create a 1D array of random values from a normal distribution with mean 0 and standard deviation 1
i = np.random.randn(5)
print(i)

[ 1.97327884 -0.76035043  2.11508682  0.36488512  0.82097767]


In [17]:
# Create a 2D array of random values from a normal distribution with mean 5 and standard deviation 2 with 2 rows and 3 columns
j = np.random.normal(loc=5, scale=2, size=(2, 3))
print(j)

[[1.59347272 5.04411536 3.69357485]
 [2.46554176 5.98257136 6.31026425]]


In [18]:
# Create a 2D array of the value 5 with 3 rows and 4 columns
k = np.full(shape=(3, 4), fill_value=5)
print(k)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# Create a 1D array of 10 equally spaced values between 0 and 1
l = np.linspace(start=0, stop=1, num=10)
print(l)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Reshaping Arrays

NumPy arrays can be reshaped to have a different number of dimensions or a different shape using the `reshape` method. This method returns a new array with the same data but a different shape.

In [20]:
# Create a 1D array with 6 elements
m = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2D array with 2 rows and 3 columns
n = m.reshape((2, 3))

print(n)

[[1 2 3]
 [4 5 6]]


In [21]:
# Create a 2D array with 2 rows and 6 columns
o = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

# Reshape the array into a 3D array with 2 layers, 2 rows, and 3 columns
p = o.reshape((2, 2, 3))

print(p)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array operations and methods
NumPy arrays can perform a wide range of mathematical and logical operations. It also has aggregations and statistical functions. Here are some of the most common operations and methods that can be performed on arrays:

### Element-wise arithmetic operations
These operations apply a mathematical operation to each element in the array. Some common element-wise arithmetic operations include addition (+), subtraction (-), multiplication (*), and division (/).

In [22]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Add the arrays element-wise
c = a + b

print(c)

[5 7 9]


### Matrix multiplication
Matrix multiplication is a mathematical operation that combines two matrices to produce a new matrix. NumPy provides several functions for performing matrix multiplication, including dot and matmul.

In [23]:
# Create two matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Multiply the matrices using matmul
c = np.matmul(a, b)

print(c)

[[19 22]
 [43 50]]


### Comparison operations 
Comparison operations compare the elements of two arrays and return a new array of Boolean values indicating the result of the comparison. Some common comparison operations include greater than (>), less than (<), equal to (==), and not equal to (!=).

In [24]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# Compare the arrays element-wise
c = a > b

print(c)

[False False  True]


### Logical operations
Logical operations apply Boolean logic to two arrays and return a new array of Boolean values indicating the result of the logical operation. Some common logical operations include AND (&), OR (|), and NOT (~).

In [25]:
# Create two arrays
a = np.array([True, False, True])
b = np.array([False, True, True])

# Apply a logical operation to the arrays element-wise
c = a & b

print(c)

[False False  True]


### Aggregation and Statistical methods
NumPy includes a wide range of aggregation and statistical functions for analyzing and manipulating data. Some common statistical functions include sum, minimum, maximum, mean, median, standard deviation, variance, and correlation.

In [27]:
# Create an array of random values
a = np.random.rand(5)

# Compute the sum of the array
print(f'sum: {(np.sum(a)).round(2)}')

# Compute the maximum value in the array
print(f'max value: {(np.max(a).round(2))}')

# Compute the minimum value in the array
print(f'min value: {(np.min(a).round(2))}')

# Compute the mean of the array
print(f'mean: {(np.mean(a).round(2))}')

# Compute the median of the array
print(f'median: {(np.median(a).round(2))}')

# Compute the standard deviation of the array
print(f'standard deviation: {(np.std(a).round(2))}')

# Compute the variance of the array
print(f'variance: {(np.var(a).round(2))}')

sum: 2.93
max value: 0.97
min value: 0.16
mean: 0.59
median: 0.43
standard deviation: 0.32
variance: 0.1


In [28]:
# Create a 2D array
f = np.array([[1, 2, 3], [4, 5, 6]])

# Compute the correlation between the two rows
g = np.corrcoef(f[0], f[1])
print(g)

[[1. 1.]
 [1. 1.]]


### Array manipulation functions
NumPy includes several functions for manipulating arrays. Some common array manipulation functions include concatenate, vertical and horizontal stack,

In [29]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate the arrays
c = np.concatenate((a, b))
print(f'Concatenated arrays:\n {c}')

# Stack the arrays vertically
d = np.vstack((a, b))
print(f'Vertically stacked:\n {d}')

# Stack the arrays horizontally
e = np.hstack((a, b))
print(f'Horizontally stacked:\n {e}')


Concatenated arrays:
 [1 2 3 4 5 6]
Vertically stacked:
 [[1 2 3]
 [4 5 6]]
Horizontally stacked:
 [1 2 3 4 5 6]


### Masks

A mask is a Boolean array that is used to filter an array based on certain conditions. In NumPy, masks are often used to extract or modify specific elements of an array based on their values.

In [30]:
# Create an array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a mask
mask = a >= 5

# Apply the mask to the array
b = a[mask]

print(b)

[5 6 7 8 9]


Masks can also be used to modify specific elements of an array based on their values. Here is an example of using a mask to set the elements of an array that are less than 5 to 0:

In [31]:
# Create an array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a mask
mask = a < 5

# Set the elements of the array that satisfy the condition to 0
a[mask] = 0

print(a)

[0 0 0 0 5 6 7 8 9]


#### Hope this helps! 
Created by: Kimberly Negrette B. June 2023 
Linkedin: www.linkedin.com/in/kimberly-negrette/